export const DATA = [
  {
    id: 1,
    firstName: "Reed",
    lastName: "Twining",
    email: "rtwining0@hhs.gov",
    gender: "Male",
    country: "Portugal",
  },
  {
    id: 2,
    firstName: "Herschel",
    lastName: "McKeachie",
    email: "hmckeachie1@baidu.com",
    gender: "Male",
    country: "Indonesia",
  },
  {
    id: 3,
    firstName: "Elsbeth",
    lastName: "Kaasmann",
    email: "ekaasmann2@sphinn.com",
    gender: "Female",
    country: "Russia",
  },
  {
    id: 4,
    firstName: "Misty",
    lastName: "Filip",
    email: "mfilip3@hud.gov",
    gender: "Female",
    country: "United Kingdom",
  },
  {
    id: 5,
    firstName: "Enoch",
    lastName: "Darnbrook",
    email: "edarnbrook4@thetimes.co.uk",
    gender: "Male",
    country: "Canada",
  },
  {
    id: 6,
    firstName: "Richardo",
    lastName: "Winckworth",
    email: "rwinckworth5@google.ru",
    gender: "Male",
    country: "Russia",
  },
  {
    id: 7,
    firstName: "Sharai",
    lastName: "Bute",
    email: "sbute6@japanpost.jp",
    gender: "Female",
    country: "China",
  },
  {
    id: 8,
    firstName: "Bay",
    lastName: "Petrashov",
    email: "bpetrashov7@cbc.ca",
    gender: "Male",
    country: "Czech Republic",
  },
  {
    id: 9,
    firstName: "Taffy",
    lastName: "Klesl",
    email: "tklesl8@typepad.com",
    gender: "Female",
    country: "Brazil",
  },
  {
    id: 10,
    firstName: "Vernon",
    lastName: "Pawson",
    email: "vpawson9@oracle.com",
    gender: "Male",
    country: "Russia",
  },
  {
    id: 11,
    firstName: "Rochelle",
    lastName: "Cordsen",
    email: "rcordsena@ucsd.edu",
    gender: "Female",
    country: "Russia",
  },
  {
    id: 12,
    firstName: "Xenia",
    lastName: "Middas",
    email: "xmiddasb@w3.org",
    gender: "Female",
    country: "Colombia",
  },
  {
    id: 13,
    firstName: "Yardley",
    lastName: "Leggett",
    email: "yleggettc@tripadvisor.com",
    gender: "Male",
    country: "Ukraine",
  },
  {
    id: 14,
    firstName: "Sauveur",
    lastName: "Blanchette",
    email: "sblanchetted@eepurl.com",
    gender: "Male",
    country: "Croatia",
  },
  {
    id: 15,
    firstName: "Saw",
    lastName: "Arpur",
    email: "sarpure@ca.gov",
    gender: "Male",
    country: "Finland",
  }
];
